### ISSUE TITLE
Route Not defined

### ISSUE THREAD

**Issue by carlosaroca** [victorybiz/laravel-crypto-payment-gateway#2]
When I put the code in Web.php show this error, 

![image](https://user-images.githubusercontent.com/42590499/141155675-92b335a6-ab14-4e63-ac3d-0ae57877ab6b.png)

I do the publish and is not working yet

 • `App\Http\Controllers\Victorybiz\LaravelCryptoPaymentGateway\src\Http\Controllers\CryptoPaymentController` was not found: Controller class `App\Http\Controllers\Victorybiz\LaravelCryptoPaymentGateway\src\Http\Controllers\CryptoPaymentController` for one of your routes was not found. Are you sure this controller exists and is imported correctly?

I neeed publish the files manually?

**Comment by carlosaroca** [comment]
Sorry, was my bad. Laravel 8 is with route namespace by default, so you need put in null if you make a upgrade from other version

**Comment by macleash90** [comment]
> Sorry, was my bad. Laravel 8 is with route namespace by default, so you need put in null if you make a upgrade from other version

I got stuck here, but did not understand what you meant by ' so you need put in null'. With some research I realized that in `App/Providers/RouteServiceProvider.php` , I had to change `protected $namespace = 'App\Http\Controllers';` to `protected $namespace = null;`
That solved it for me. Thank you
